# Generated by Django 4.2 on 2023-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_level',
            field=models.CharField(default='----', max_length=99),
        ),
    ]
